# Generated by Django 4.1.9 on 2023-07-16 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='winner',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
