# Generated by Django 4.1.9 on 2023-07-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_auctionlisting_winner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='starting_bid',
            new_name='starting_price',
        ),
    ]
